# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  CreateMarkdownDocs:
    runs-on: ubuntu-latest
    name: Create Markdown Documentation Files
    steps:
      - uses: actions/checkout@v2
      - name: Generate Python Docs
        uses: jbheard/markdown-docs@v1
      - name: Open docs update PR
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  CreateAutomaticRequirements:
    runs-on: ubuntu-latest
    name: Create requirements.txt from file
    steps:
      - uses: actions/checkout@v2
      - name: Create requirements.txt
        uses: ryan-rozario/pipreqs-action-cpy@master
  RunPylint:
    runs-on: ubuntu-latest
    name: Run Pylint check
    steps:
      - name: GitHub Action for pylint
        uses: cclauss/GitHub-Action-for-pylint@0.7.0




     
