# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  PythonRun:
    runs-on: ubuntu-latest
    name: Do all Python stuff
    steps:
    - name: Python Markdown Documentation
      uses: jbheard/markdown-docs@v0.1
    - name: Automatic requirement.txt for Python Projects
      uses: ryan-rozario/pipreqs-action@v1.0.1
    - name: pylint3-action
      uses: LakshitF/pylint3-action@v2


     
